
TRAIN_START_DATE = "2012-04-01"
TRAIN_END_DATE = "2013-04-01"
BACKTEST_END_DATA = "2021-04-10"
PREDICT_PERIOD = 20
W_MEAN = 1
W_STD = 0
GENERATION_NUM = 10
PARALLEL_NUM = 10
COMPOSITE_FACTOR = ['adjusted_profit_to_total_profit_ttm','capital_reserve_per_share_ttm','cash_equivalent_per_share_ttm',
                    'cash_flow_per_share_ttm','cost_to_sales_ttm','du_profit_margin_ttm','earned_reserve_per_share_ttm','ebitda_ttm',
                     'ebit_per_share_ttm','expense_to_revenue_ttm','gross_profit_margin_ttm','investment_profit_to_profit_before_tax_ttm',
                    'net_profit_to_revenue_ttm','non_operating_profit_to_profit_before_tax_ttm','operating_cash_flow_per_share_ttm',
                    'operating_profit_to_profit_before_tax_ttm','operating_total_revenue_per_share_ttm','return_on_asset_ttm',
                    'return_on_equity_ttm','return_on_invested_capital_ttm','surplus_cash_protection_multiples_ttm',
                    'book_leverage_ttm', 'cash_ratio_ttm','current_debt_to_total_debt_ttm','current_ratio_ttm', 'debt_to_asset_ratio_ttm',
                    'ebitda_to_debt_ttm', 'equity_ratio_ttm','equity_to_interest_bearing_debt_ttm','long_term_debt_to_working_capital_ttm',
                    'non_current_asset_to_total_asset_ttm','non_current_debt_to_total_debt_ttm', 'non_interest_bearing_current_debt_ttm',
                    'non_interest_bearing_non_current_debt_ttm', 'ocf_to_current_ratio_ttm','ocf_to_net_debt_ttm','time_interest_earned_ratio_ttm',
                    'book_to_market_ratio_ttm', 'book_value_per_share_ttm', 'dividend_yield_ttm', 'ep_ratio_ttm',
                    'ev_to_ebitda_ttm', 'ev_ttm','free_cash_flow_equity_per_share_ttm',
                    'pb_ratio_ttm', 'pcf_ratio_total_ttm', 'pcf_ratio_ttm', 'peg_ratio_ttm', 'pe_ratio_ttm','ps_ratio_ttm',
                    'account_receivable_turnover_days_ttm', 'account_receivable_turnover_rate_ttm',
                    'current_asset_turnover_ttm', 'equity_fixed_asset_ratio_ttm', 'equity_turnover_ratio_ttm','fixed_asset_ratio_ttm',
                    'fixed_asset_turnover_ttm', 'intangible_asset_ratio_ttm', 'inventory_turnover_ttm','invested_capital_ttm',
                    'net_working_capital_ttm', 'operating_cycle_ttm', 'tangible_asset_per_share_ttm','working_capital_ttm',
                    'diluted_common_stock_ttm','total_mv','gross_profit_growth_ratio_ttm', 'inc_book_per_share_ttm',
                    'inc_revenue_ttm','net_asset_growth_ratio_ttm', 'net_cash_flow_growth_ratio_ttm',
                    'net_financing_cash_flow_growth_ratio_ttm','net_investing_cash_flow_growth_ratio_ttm',
                    'net_operate_cash_flow_growth_ratio_ttm','profit_growth_ratio_ttm', 'total_asset_growth_ratio_ttm','total_asset_turnover_ttm',
                    'ADX', 'DX','MINUS_DI', 'MINUS_DM', 'MOM', 'RSI', 'S-RSId','TRIX', 'ULTOSC', 'ret', 'ret_lag1', 'ret_lag2',
                    'AD', 'ADOSC', 'OBV', 'volume_pct', 'volume_std','ATR', 'NATR', 'TRANGE_1', 'TRANGE_2', 'TRANGE_3', 'TRANGE_4', 'volatility_1', 'volatility_2',
                     'volatility_3', 'volatility_4']


FACTOR_CATEGORY = {"profitability": ['adjusted_fully_diluted_earnings_per_share_ttm',
                                     'adjusted_profit_to_total_profit_ttm',
                                     'capital_reserve_per_share_ttm','cash_equivalent_per_share_ttm','cash_flow_per_share_ttm',
                                     'cfp_ratio_ttm','cost_to_sales_ttm','du_profit_margin_ttm',
                                     'du_return_on_equity_ttm','earned_reserve_per_share_ttm','ebitda_ttm',
                                     'ebit_per_share_ttm','expense_to_revenue_ttm','fcfe_ttm',
                                     'fcff_ttm','free_cash_flow_company_per_share_ttm', 'gross_profit_margin_ttm','income_from_main_operations_ttm',
                                     'investment_profit_to_profit_before_tax_ttm','net_profit_to_revenue_ttm',
                                     'non_operating_profit_to_profit_before_tax_ttm','operating_cash_flow_per_share_ttm','operating_profit_to_profit_before_tax_ttm',
                                     'operating_total_revenue_per_share_ttm','profit_from_operation_to_revenue_ttm',
                                     'retained_earnings_per_share_ttm','retained_earnings_ttm',
                                     'return_on_asset_ttm','return_on_equity_ttm','return_on_invested_capital_ttm',
                                     'sp_ratio_ttm','surplus_cash_protection_multiples_ttm','total_mv'],
                   "levarage": ['book_leverage_ttm','capital_to_equity_ratio_ttm','cash_ratio_ttm','current_debt_to_total_debt_ttm',
                                'current_ratio_ttm','debt_to_asset_ratio_ttm','debt_to_equity_ratio_ttm','interest_bearing_debt_to_capital_ttm',
                                'du_equity_multiplier_ttm','ebitda_to_debt_ttm','equity_multiplier_ttm','equity_ratio_ttm',
                                'equity_to_debt_ratio_ttm','equity_to_interest_bearing_debt_ttm','interest_bearing_debt_ttm','liabilities_per_share_ttm',
                                'long_term_debt_to_working_capital_ttm','market_leverage_ttm','net_debt_ttm','non_current_asset_to_total_asset_ttm',
                                'non_current_debt_to_total_debt_ttm','non_interest_bearing_current_debt_ttm',
                                'non_interest_bearing_non_current_debt_ttm','ocf_to_current_ratio_ttm','ocf_to_debt_ttm',
                                'ocf_to_interest_bearing_debt_ttm','ocf_to_net_debt_ttm','quick_ratio_ttm','time_interest_earned_ratio_ttm',
                                'total_mv'],
                   "value": ['book_to_market_ratio_ttm','book_value_per_share_ttm','dividend_yield_ttm','ep_ratio_ttm',
                             'ev_no_cash_to_ebit_ttm','ev_no_cash_ttm','ev_to_ebitda_ttm','ev_ttm','free_cash_flow_equity_per_share_ttm',
                             'pb_ratio_ttm','pcf_ratio_total_ttm','pcf_ratio_ttm','peg_ratio_ttm','pe_ratio_ttm','ps_ratio_ttm','total_mv'],
                   "operation":['account_receivable_turnover_days_ttm','account_receivable_turnover_rate_ttm',
                                'current_asset_turnover_ttm','equity_fixed_asset_ratio_ttm','equity_turnover_ratio_ttm','fixed_asset_ratio_ttm',
                                'fixed_asset_turnover_ttm','intangible_asset_ratio_ttm','inventory_turnover_ttm','invested_capital_ttm',
                                'net_working_capital_ttm','operating_cycle_ttm','tangible_asset_per_share_ttm','working_capital_ttm','total_mv'],
                   "size":['diluted_common_stock_ttm','weighted_common_stock_ttm','total_mv'],
                   "growth": ['gross_profit_growth_ratio_ttm','inc_book_per_share_ttm','inc_return_on_equity_ttm','inc_revenue_ttm',
                              'net_asset_growth_ratio_ttm','net_cash_flow_growth_ratio_ttm','net_financing_cash_flow_growth_ratio_ttm',
                              'net_investing_cash_flow_growth_ratio_ttm','net_operate_cash_flow_growth_ratio_ttm',
                              'net_profit_growth_ratio_ttm','net_profit_parent_company_growth_ratio_ttm','operating_profit_growth_ratio_ttm',
                              'operating_revenue_growth_ratio_ttm','profit_growth_ratio_ttm','total_asset_growth_ratio_ttm','total_asset_turnover_ttm',
                              'total_mv'],
                   "momentum": ['ADX', 'ADXR', 'APO', 'CCI', 'CMO', 'DX', 'macd1', 'macdsignal1',
                                'MFI', 'MINUS_DI', 'MINUS_DM', 'MOM', 'PLUS_DI', 'PLUS_DM', 'PPO', 'RSI', 'S-RSId',
                                'TRIX', 'ULTOSC', 'ret', 'ret_lag1', 'ret_lag2', 'total_mv'],
                   "volume": ['AD', 'ADOSC', 'OBV', 'volume_pct', 'volume_std', 'total_mv'],
                   "volatility": ['ATR', 'NATR', 'TRANGE_1', 'TRANGE_2', 'TRANGE_3', 'TRANGE_4', 'volatility_1', 'volatility_2',
                                  'volatility_3', 'volatility_4', 'total_mv'],
                   "composite_factor":COMPOSITE_FACTOR}


# FACTOR_CATEGORY = {"profitability": ['adjusted_fully_diluted_earnings_per_share_ttm','adjusted_earnings_per_share_ttm',
#                                      'adjusted_profit_to_total_profit_ttm','adjusted_return_on_equity_diluted_ttm','adjusted_return_on_equity_ttm',
#                                      'capital_reserve_per_share_ttm','cash_equivalent_per_share_ttm','cash_flow_per_share_ttm',
#                                      'cfp_ratio_ttm','cost_to_sales_ttm','diluted_earnings_per_share_ttm','du_profit_margin_ttm',
#                                      'du_return_on_equity_ttm','du_return_on_sales_ttm','earned_reserve_per_share_ttm','ebitda_ttm',
#                                      'ebit_per_share_ttm','ebit_to_revenue_ttm','ebit_ttm','expense_to_revenue_ttm','fcfe_ttm',
#                                      'fcff_ttm','free_cash_flow_company_per_share_ttm', 'gross_profit_margin_ttm','income_from_main_operations_ttm',
#                                      'investment_profit_to_profit_before_tax_ttm','net_profit_margin_ttm','net_profit_to_revenue_ttm',
#                                      'non_operating_profit_to_profit_before_tax_ttm','operating_cash_flow_per_share_ttm','operating_profit_to_profit_before_tax_ttm',
#                                      'operating_revenue_per_share_ttm','operating_total_revenue_per_share_ttm','profit_from_operation_to_revenue_ttm',
#                                      'retained_earnings_per_share_ttm','retained_earnings_ttm','return_on_asset_net_profit_ttm',
#                                      'return_on_asset_ttm','return_on_equity_diluted_ttm','return_on_equity_ttm','return_on_invested_capital_ttm',
#                                      'sp_ratio_ttm','surplus_cash_protection_multiples_ttm','total_mv'],
#                    "levarage": ['book_leverage_ttm','capital_to_equity_ratio_ttm','cash_ratio_ttm','current_debt_to_total_debt_ttm',
#                                 'current_ratio_ttm','debt_to_asset_ratio_ttm','debt_to_equity_ratio_ttm','interest_bearing_debt_to_capital_ttm',
#                                 'du_equity_multiplier_ttm','ebitda_to_debt_ttm','equity_multiplier_ttm','equity_ratio_ttm',
#                                 'equity_to_debt_ratio_ttm','equity_to_interest_bearing_debt_ttm','interest_bearing_debt_ttm','liabilities_per_share_ttm',
#                                 'long_term_debt_to_working_capital_ttm','market_leverage_ttm','net_debt_ttm','non_current_asset_to_total_asset_ttm',
#                                 'non_current_debt_to_total_debt_ttm','non_interest_bearing_current_debt_ttm',
#                                 'non_interest_bearing_non_current_debt_ttm','ocf_to_current_ratio_ttm','ocf_to_debt_ttm',
#                                 'ocf_to_interest_bearing_debt_ttm','ocf_to_net_debt_ttm','quick_ratio_ttm','time_interest_earned_ratio_ttm',
#                                 'total_mv'],
#                    "value": ['book_to_market_ratio_ttm','book_value_per_share_ttm','dividend_yield_ttm','ep_ratio_ttm',
#                              'ev_no_cash_to_ebit_ttm','ev_no_cash_ttm','ev_to_ebitda_ttm','ev_ttm','free_cash_flow_equity_per_share_ttm',
#                              'pb_ratio_ttm','pcf_ratio_total_ttm','pcf_ratio_ttm','peg_ratio_ttm','pe_ratio_ttm','ps_ratio_ttm','total_mv'],
#                    "operation":['account_receivable_turnover_days_ttm','account_receivable_turnover_rate_ttm',
#                                 'current_asset_turnover_ttm','equity_fixed_asset_ratio_ttm','equity_turnover_ratio_ttm','fixed_asset_ratio_ttm',
#                                 'fixed_asset_turnover_ttm','intangible_asset_ratio_ttm','inventory_turnover_ttm','invested_capital_ttm',
#                                 'net_working_capital_ttm','operating_cycle_ttm','tangible_asset_per_share_ttm','working_capital_ttm','total_mv'],
#                    "size":['diluted_common_stock_ttm','weighted_common_stock_ttm','total_mv'],
#                    "growth": ['gross_profit_growth_ratio_ttm','inc_book_per_share_ttm','inc_return_on_equity_ttm','inc_revenue_ttm',
#                               'net_asset_growth_ratio_ttm','net_cash_flow_growth_ratio_ttm','net_financing_cash_flow_growth_ratio_ttm',
#                               'net_investing_cash_flow_growth_ratio_ttm','net_operate_cash_flow_growth_ratio_ttm',
#                               'net_profit_growth_ratio_ttm','net_profit_parent_company_growth_ratio_ttm','operating_profit_growth_ratio_ttm',
#                               'operating_revenue_growth_ratio_ttm','profit_growth_ratio_ttm','total_asset_growth_ratio_ttm','total_asset_turnover_ttm',
#                               'total_mv'],
#                    "momentum": ['ADX', 'ADXR', 'APO', 'CCI', 'CMO', 'DX', 'macd1', 'macdsignal1',
#                                 'MFI', 'MINUS_DI', 'MINUS_DM', 'MOM', 'PLUS_DI', 'PLUS_DM', 'PPO', 'RSI', 'S-RSId',
#                                 'TRIX', 'ULTOSC', 'ret', 'ret_lag1', 'ret_lag2', 'total_mv'],
#                    "volume": ['AD', 'ADOSC', 'OBV', 'volume_pct', 'volume_std', 'total_mv'],
#                    "volatility": ['ATR', 'NATR', 'TRANGE_1', 'TRANGE_2', 'TRANGE_3', 'TRANGE_4', 'volatility_1', 'volatility_2',
#                                   'volatility_3', 'volatility_4', 'total_mv']}